/**
 * データソース: マルチエキューブ（JR東日本スマートロジスティクス運営 multiecube.com）。
 * フロントエンドが呼んでいる公開JSON API（https://api.multiecube.com/v1/location/ph2）を
 * 直接呼び出す。会員登録・ログイン不要で取得できる、サイト上に表示されているのと
 * 同じロッカー設置情報のみを対象とし、予約・決済等の機能には一切関与しない。
 *
 * リアルタイムの空き数（unreserve.num_empty等）は取得・保存しない。各サイズの
 * 設置個数（num_total、日々変動しない静的な値）のみを記録する方針とした
 * （2026-07-12、ユーザー判断）。刻一刻と変わる商用の空き状況ではなく、
 * 変化の少ない設置数のみを扱うことで、規約上のリスクをさらに下げる狙い。
 *
 * 利用規約・robots.txtにはスクレイピング/自動アクセスを明示的に禁止する記載がない
 * ことをPlaywrightでレンダリングして確認済み（2026-07-12）。ただし規約の沈黙は
 * 明示的な許可ではないため、負荷をかけないよう駅単位・低頻度でのみ実行すること。
 *
 * - facility_idはマルチエキューブ側のロッカーID（loc.id）をそのまま使う。
 *   彼らのシステム内で一意・安定しているため、写真投稿機能等が参照する
 *   facility_idとして継続利用できる。
 */

const { todayJstDate } = require("../lib/time");

const API_BASE = "https://api.multiecube.com/v1/location/ph2";
const SOURCE_SITE_NAME = "マルチエキューブ（JR東日本スマートロジスティクス）";

// 対象駅とマルチエキューブ側のbase_id（2026-07-12にAPIから特定）
const STATIONS = [
  { slug: "ikebukuro", name: "池袋駅", baseId: 35 },
  { slug: "shinjuku", name: "新宿駅", baseId: 41 },
  { slug: "shibuya", name: "渋谷駅", baseId: 46 },
  { slug: "tokyo", name: "東京駅", baseId: 32 },
  { slug: "shinagawa", name: "品川駅", baseId: 36 },
  { slug: "ueno", name: "上野駅", baseId: 40 },
  { slug: "yokohama", name: "横浜駅", baseId: 44 },
  { slug: "omiya", name: "大宮駅", baseId: 87 },
  { slug: "shimbashi", name: "新橋駅", baseId: 57 },
  { slug: "akihabara", name: "秋葉原駅", baseId: 34 },
  { slug: "kita-senju", name: "北千住駅", baseId: 165 },
  { slug: "kawasaki", name: "川崎駅", baseId: 155 },
  { slug: "takadanobaba", name: "高田馬場駅", baseId: 81 },
  { slug: "tachikawa", name: "立川駅", baseId: 163 },
  { slug: "osaki", name: "大崎駅", baseId: 53 },
  { slug: "hamamatsucho", name: "浜松町駅", baseId: 37 },
  { slug: "nakano", name: "中野駅", baseId: 93 },
  { slug: "kichijoji", name: "吉祥寺駅", baseId: 148 },
  { slug: "yurakucho", name: "有楽町駅", baseId: 58 },
  { slug: "ebisu", name: "恵比寿駅", baseId: 45 },
  { slug: "tamachi", name: "田町駅", baseId: 63 },
  { slug: "kamata", name: "蒲田駅", baseId: 61 },
  { slug: "kashiwa", name: "柏駅", baseId: 182 },
  { slug: "musashi-kosugi", name: "武蔵小杉駅", baseId: 123 },
  { slug: "gotanda", name: "五反田駅", baseId: 55 },
  { slug: "nippori", name: "日暮里駅", baseId: 48 },
  { slug: "chiba", name: "千葉駅", baseId: 216 },
  { slug: "fujisawa", name: "藤沢駅", baseId: 137 },
  { slug: "kokubunji", name: "国分寺駅", baseId: 178 },
  { slug: "totsuka", name: "戸塚駅", baseId: 119 },
  { slug: "machida", name: "町田駅", baseId: 164 },
  { slug: "akabane", name: "赤羽駅", baseId: 47 },
  { slug: "meguro", name: "目黒駅", baseId: 66 },
  { slug: "sendai", name: "仙台駅", baseId: 43 },
  { slug: "ofuna", name: "大船駅", baseId: 152 },
  { slug: "urawa", name: "浦和駅", baseId: 101 },
  { slug: "kanda", name: "神田駅", baseId: 33 },
  { slug: "matsudo", name: "松戸駅", baseId: 199 },
  { slug: "nishi-nippori", name: "西日暮里駅", baseId: 73 },
  { slug: "tsudanuma", name: "津田沼駅", baseId: 94 },
  { slug: "yotsuya", name: "四ツ谷駅", baseId: 67 },
  { slug: "ochanomizu", name: "御茶ノ水駅", baseId: 92 },
  { slug: "oimachi", name: "大井町駅", baseId: 62 },
  { slug: "mitaka", name: "三鷹駅", baseId: 214 },
  { slug: "omori", name: "大森駅", baseId: 74 },
  { slug: "ogikubo", name: "荻窪駅", baseId: 78 },
  { slug: "maihama", name: "舞浜駅", baseId: 39 },
  { slug: "musashi-mizonokuchi", name: "武蔵溝ノ口駅", baseId: 150 },
  { slug: "noborito", name: "登戸駅", baseId: 151 },
  { slug: "hachioji", name: "八王子駅", baseId: 99 },
  { slug: "kawaguchi", name: "川口駅", baseId: 154 },
  { slug: "shin-koiwa", name: "新小岩駅", baseId: 64 },
  { slug: "sakuragicho", name: "桜木町駅", baseId: 398 },
  { slug: "tsurumi", name: "鶴見駅", baseId: 159 },
  { slug: "suidobashi", name: "水道橋駅", baseId: 68 },
  { slug: "iidabashi", name: "飯田橋駅", baseId: 77 },
  { slug: "harajuku", name: "原宿駅", baseId: 56 },
  { slug: "sugamo", name: "巣鴨駅", baseId: 71 },
  { slug: "musashi-sakai", name: "武蔵境駅", baseId: 103 },
  { slug: "okachimachi", name: "御徒町駅", baseId: 59 },
  { slug: "hashimoto", name: "橋本駅", baseId: 221 },
  { slug: "oji", name: "王子駅", baseId: 85 },
  { slug: "kaihin-makuhari", name: "海浜幕張駅", baseId: 225 },
  { slug: "musashi-koganei", name: "武蔵小金井駅", baseId: 127 },
  { slug: "hiratsuka", name: "平塚駅", baseId: 108 },
  { slug: "yoyogi", name: "代々木駅", baseId: 75 },
  { slug: "ichikawa", name: "市川駅", baseId: 51 },
  { slug: "tsujido", name: "辻堂駅", baseId: 121 },
  { slug: "nagatsuta", name: "長津田駅", baseId: 192 },
  { slug: "warabi", name: "蕨駅", baseId: 118 },
  { slug: "minami-urawa", name: "南浦和駅", baseId: 266 },
  { slug: "motoyawata", name: "本八幡駅", baseId: 52 },
  { slug: "kameido", name: "亀戸駅", baseId: 50 },
  { slug: "nishi-kawaguchi", name: "西川口駅", baseId: 222 },
  { slug: "otsuka", name: "大塚駅", baseId: 83 },
  { slug: "saitama-shintoshin", name: "さいたま新都心駅", baseId: 156 },
  { slug: "kannai", name: "関内駅", baseId: 179 },
  { slug: "chigasaki", name: "茅ケ崎駅", baseId: 122 },
  { slug: "higashi-totsuka", name: "東戸塚駅", baseId: 100 },
  { slug: "shin-urayasu", name: "新浦安駅", baseId: 217 },
  { slug: "ichigaya", name: "市ケ谷駅", baseId: 147 },
  { slug: "musashi-urawa", name: "武蔵浦和駅", baseId: 144 },
  { slug: "asakusabashi", name: "浅草橋駅", baseId: 174 },
  { slug: "kanamachi", name: "金町駅", baseId: 212 },
  { slug: "kunitachi", name: "国立駅", baseId: 120 },
  { slug: "kita-urawa", name: "北浦和駅", baseId: 193 },
  { slug: "koenji", name: "高円寺駅", baseId: 79 },
  { slug: "inage", name: "稲毛駅", baseId: 259 },
  { slug: "komagome", name: "駒込駅", baseId: 84 },
  { slug: "nishi-ogikubo", name: "西荻窪駅", baseId: 69 },
  { slug: "takanawa-gateway", name: "高輪ゲートウェイ駅", baseId: 38 },
  { slug: "shinanomachi", name: "信濃町駅", baseId: 42 },
  { slug: "ryogoku", name: "両国駅", baseId: 49 },
  { slug: "nishi-funabashi", name: "西船橋駅", baseId: 54 },
  { slug: "uguisudani", name: "鶯谷駅", baseId: 60 },
  { slug: "mejiro", name: "目白駅", baseId: 70 },
  { slug: "tabata", name: "田端駅", baseId: 72 },
  { slug: "sendagaya", name: "千駄ヶ谷駅", baseId: 76 },
  { slug: "higashi-nakano", name: "東中野駅", baseId: 80 },
  { slug: "itabashi", name: "板橋駅", baseId: 82 },
  { slug: "kamakura", name: "鎌倉駅", baseId: 86 },
  { slug: "atami", name: "熱海駅", baseId: 89 },
  { slug: "hatchobori", name: "八丁堀駅", baseId: 90 },
  { slug: "asagaya", name: "阿佐ヶ谷駅", baseId: 95 },
  { slug: "etchujima", name: "越中島駅", baseId: 96 },
  { slug: "utsunomiya", name: "宇都宮駅", baseId: 97 },
  { slug: "hodogaya", name: "保土ヶ谷駅", baseId: 98 },
  { slug: "hirai", name: "平井駅", baseId: 102 },
  { slug: "makuhari", name: "幕張駅", baseId: 104 },
  { slug: "kamoi", name: "鴨居駅", baseId: 105 },
  { slug: "shin-kemigawa", name: "新検見川駅", baseId: 106 },
  { slug: "oyama", name: "小山駅", baseId: 107 },
  { slug: "otsuki", name: "大月駅", baseId: 109 },
  { slug: "fuchu-hommachi", name: "府中本町駅", baseId: 110 },
  { slug: "shin-kawasaki", name: "新川崎駅", baseId: 112 },
  { slug: "haijima", name: "拝島駅", baseId: 113 },
  { slug: "nishi-fuchu", name: "西府駅", baseId: 114 },
  { slug: "kawabe", name: "河辺駅", baseId: 116 },
  { slug: "kita-akabane", name: "北赤羽駅", baseId: 117 },
  { slug: "nishi-tachikawa", name: "西立川駅", baseId: 124 },
  { slug: "hino", name: "日野駅", baseId: 125 },
  { slug: "higashi-koganei", name: "東小金井駅", baseId: 126 },
  { slug: "toyoda", name: "豊田駅", baseId: 128 },
  { slug: "odawara", name: "小田原駅", baseId: 129 },
  { slug: "niiza", name: "新座駅", baseId: 130 },
  { slug: "nishi-hachioji", name: "西八王子駅", baseId: 131 },
  { slug: "ukima-funado", name: "浮間舟渡駅", baseId: 132 },
  { slug: "shin-nihombashi", name: "新日本橋駅", baseId: 133 },
  { slug: "isogo", name: "磯子駅", baseId: 134 },
  { slug: "hasuda", name: "蓮田駅", baseId: 135 },
  { slug: "mikawashima", name: "三河島駅", baseId: 136 },
  { slug: "inagi-naganuma", name: "稲城長沼駅", baseId: 138 },
  { slug: "higashi-jujo", name: "東十条駅", baseId: 139 },
  { slug: "minami-tama", name: "南多摩駅", baseId: 140 },
  { slug: "kita-toda", name: "北戸田駅", baseId: 141 },
  { slug: "nishi-kokubunji", name: "西国分寺駅", baseId: 142 },
  { slug: "kita-fuchu", name: "北府中駅", baseId: 143 },
  { slug: "naka-urawa", name: "中浦和駅", baseId: 145 },
  { slug: "shin-kodaira", name: "新小平駅", baseId: 146 },
  { slug: "musashi-nakahara", name: "武蔵中原駅", baseId: 149 },
  { slug: "konandai", name: "港南台駅", baseId: 157 },
  { slug: "negishi", name: "根岸駅", baseId: 158 },
  { slug: "yugawara", name: "湯河原駅", baseId: 160 },
  { slug: "kikuna", name: "菊名駅", baseId: 162 },
  { slug: "tokyo-monorail-haneda-airport-terminal-3", name: "東京モノレール 羽田空港第3ターミナル駅", baseId: 166 },
  { slug: "tokyo-monorail-haneda-airport-terminal-1", name: "東京モノレール 羽田空港第1ターミナル駅", baseId: 167 },
  { slug: "tokyo-monorail-haneda-airport-terminal-2", name: "東京モノレール 羽田空港第2ターミナル駅", baseId: 168 },
  { slug: "kawagoe", name: "川越駅", baseId: 169 },
  { slug: "nishi-chiba", name: "西千葉駅", baseId: 170 },
  { slug: "musashi-itsukaichi", name: "武蔵五日市駅", baseId: 171 },
  { slug: "yanokuchi", name: "矢野口駅", baseId: 172 },
  { slug: "toda-koen", name: "戸田公園駅", baseId: 173 },
  { slug: "yono", name: "与野駅", baseId: 175 },
  { slug: "kofu", name: "甲府駅", baseId: 177 },
  { slug: "yokodai", name: "洋光台駅", baseId: 180 },
  { slug: "hongodai", name: "本郷台駅", baseId: 181 },
  { slug: "shimosa-nakayama", name: "下総中山駅", baseId: 183 },
  { slug: "kita-yono", name: "北与野駅", baseId: 184 },
  { slug: "oiso", name: "大磯駅", baseId: 185 },
  { slug: "ninomiya", name: "二宮駅", baseId: 186 },
  { slug: "ishikawacho", name: "石川町駅", baseId: 187 },
  { slug: "yono-hommachi", name: "与野本町駅", baseId: 188 },
  { slug: "tokaichiba", name: "十日市場駅", baseId: 189 },
  { slug: "kobuchi", name: "古淵駅", baseId: 190 },
  { slug: "fuchinobe", name: "淵野辺駅", baseId: 191 },
  { slug: "naruse", name: "成瀬駅", baseId: 194 },
  { slug: "keio-seiseki-sakuragaoka", name: "京王聖蹟桜ヶ丘駅", baseId: 195 },
  { slug: "keio-fuchu", name: "京王府中駅", baseId: 196 },
  { slug: "keio-hachimanyama", name: "京王八幡山駅", baseId: 197 },
  { slug: "keio-chofu", name: "京王調布駅", baseId: 198 },
  { slug: "keio-shinjuku", name: "京王新宿駅", baseId: 200 },
  { slug: "kameari", name: "亀有駅", baseId: 201 },
  { slug: "minami-yono", name: "南与野駅", baseId: 202 },
  { slug: "enzan", name: "塩山駅", baseId: 204 },
  { slug: "minami-senju", name: "南千住駅", baseId: 205 },
  { slug: "shin-matsudo", name: "新松戸駅", baseId: 206 },
  { slug: "shin-koyasu", name: "新子安駅", baseId: 207 },
  { slug: "kozu", name: "国府津駅", baseId: 208 },
  { slug: "okubo", name: "大久保駅", baseId: 209 },
  { slug: "kamakura-post-office", name: "鎌倉郵便局駅", baseId: 210 },
  { slug: "eneos-platform-hitachino-ushiku-ss", name: "ENEOSプラットフォームひたち野うしくSS駅", baseId: 211 },
  { slug: "yako", name: "矢向駅", baseId: 213 },
  { slug: "higashi-omiya", name: "東大宮駅", baseId: 215 },
  { slug: "kuki", name: "久喜駅", baseId: 218 },
  { slug: "higashi-tokorozawa", name: "東所沢駅", baseId: 219 },
  { slug: "kobuchizawa", name: "小淵沢駅", baseId: 220 },
  { slug: "higashi-funabashi", name: "東船橋駅", baseId: 223 },
  { slug: "yamanashi-shi", name: "山梨市駅", baseId: 224 },
  { slug: "ito", name: "伊東駅", baseId: 226 },
  { slug: "toro", name: "土呂駅", baseId: 227 },
  { slug: "oguchi", name: "大口駅", baseId: 228 },
  { slug: "nakayama", name: "中山駅", baseId: 229 },
  { slug: "minami-funabashi", name: "南船橋駅", baseId: 230 },
  { slug: "bakurocho", name: "馬喰町駅", baseId: 231 },
  { slug: "mobara", name: "茂原駅", baseId: 235 },
  { slug: "goi", name: "五井駅", baseId: 238 },
  { slug: "narita", name: "成田駅", baseId: 242 },
  { slug: "kita-kamakura", name: "北鎌倉駅", baseId: 243 },
  { slug: "keihan-hirakata-shi", name: "京阪 枚方市駅", baseId: 244 },
  { slug: "keihan-nakanoshima", name: "京阪 中之島駅", baseId: 245 },
  { slug: "keihan-kyobashi", name: "京阪 京橋駅", baseId: 246 },
  { slug: "keihan-kitahama", name: "京阪 北浜駅", baseId: 247 },
  { slug: "keihan-temmabashi", name: "京阪 天満橋駅", baseId: 248 },
  { slug: "mito", name: "水戸駅", baseId: 249 },
  { slug: "kyoto", name: "京都駅", baseId: 250 },
  { slug: "jujo", name: "十条駅", baseId: 251 },
  { slug: "okutama", name: "奥多摩駅", baseId: 252 },
  { slug: "kinomiya", name: "来宮駅", baseId: 253 },
  { slug: "nasushiobara", name: "那須塩原駅", baseId: 254 },
  { slug: "shin-narashino", name: "新習志野駅", baseId: 255 },
  { slug: "nikko", name: "日光駅", baseId: 256 },
  { slug: "toride", name: "取手駅", baseId: 257 },
  { slug: "kuroiso", name: "黒磯駅", baseId: 258 },
  { slug: "takasaki", name: "高崎駅", baseId: 260 },
  { slug: "kaminakazato", name: "上中里駅", baseId: 261 },
  { slug: "katsuta", name: "勝田駅", baseId: 262 },
  { slug: "makuharihongo", name: "幕張本郷駅", baseId: 263 },
  { slug: "kozukue", name: "小机駅", baseId: 264 },
  { slug: "koga", name: "古河駅", baseId: 265 },
  { slug: "shin-yokohama", name: "新横浜駅", baseId: 267 },
  { slug: "manazuru", name: "真鶴駅", baseId: 268 },
  { slug: "shin-aomori", name: "新青森駅", baseId: 271 },
  { slug: "koriyama", name: "郡山駅", baseId: 272 },
  { slug: "fukushima", name: "福島駅", baseId: 273 },
  { slug: "koshigaya-laketown", name: "越谷レイクタウン駅", baseId: 274 },
  { slug: "shin-osaka", name: "新大阪駅", baseId: 275 },
  { slug: "nishi-oi", name: "西大井駅", baseId: 276 },
  { slug: "tokyu-shibuya", name: "東急 渋谷駅", baseId: 277 },
  { slug: "tokyu-musashi-kosugi", name: "東急 武蔵小杉駅", baseId: 278 },
  { slug: "kemigawahama", name: "検見川浜駅", baseId: 279 },
  { slug: "inagekaigan", name: "稲毛海岸駅", baseId: 280 },
  { slug: "tokyu-komazawa-university", name: "東急 駒沢大学駅", baseId: 281 },
  { slug: "toda", name: "戸田駅", baseId: 282 },
  { slug: "sawara", name: "佐原駅", baseId: 283 },
  { slug: "takao", name: "高尾駅", baseId: 284 },
  { slug: "hachioji-minamino", name: "八王子みなみ野駅", baseId: 285 },
  { slug: "higashi-urawa", name: "東浦和駅", baseId: 286 },
  { slug: "funabashi-hoten", name: "船橋法典駅", baseId: 287 },
  { slug: "ushiku", name: "牛久駅", baseId: 288 },
  { slug: "ryugasaki-shi", name: "龍ケ崎市駅", baseId: 289 },
  { slug: "higashi-matsudo", name: "東松戸駅", baseId: 290 },
  { slug: "tokyu-o-okayama", name: "東急 大岡山駅", baseId: 291 },
  { slug: "minami-kashiwa", name: "南柏駅", baseId: 292 },
  { slug: "ishibashi", name: "石橋駅", baseId: 293 },
  { slug: "keihan-sanjo", name: "京阪 三条駅", baseId: 294 },
  { slug: "keihan-demachiyanagi", name: "京阪 出町柳駅", baseId: 295 },
  { slug: "keihan-gion-shijo", name: "京阪 祇園四条駅", baseId: 296 },
  { slug: "keihan-shichijo", name: "京阪 七条駅", baseId: 297 },
  { slug: "nagano", name: "長野駅", baseId: 298 },
  { slug: "misato", name: "三郷駅", baseId: 299 },
  { slug: "soga", name: "蘇我駅", baseId: 300 },
  { slug: "okegawa", name: "桶川駅", baseId: 301 },
  { slug: "kita-kashiwa", name: "北柏駅", baseId: 302 },
  { slug: "hakata", name: "博多駅", baseId: 303 },
  { slug: "kashimada", name: "鹿島田駅", baseId: 304 },
  { slug: "ichikawa-shiohama", name: "市川塩浜駅", baseId: 305 },
  { slug: "niigata", name: "新潟駅", baseId: 306 },
  { slug: "sapporo", name: "札幌駅", baseId: 307 },
  { slug: "sapporo-city-subway-odori", name: "札幌市営 大通駅", baseId: 308 },
  { slug: "sapporo-city-subway-sapporo", name: "札幌市営 さっぽろ駅", baseId: 309 },
  { slug: "shin-okubo", name: "新大久保駅", baseId: 310 },
  { slug: "aeon-mall-sendai-uesugi", name: "イオンモール仙台上杉駅", baseId: 311 },
  { slug: "fukaya", name: "深谷駅", baseId: 312 },
  { slug: "shin-akitsu", name: "新秋津駅", baseId: 313 },
  { slug: "kitamoto", name: "北本駅", baseId: 314 },
  { slug: "kumagaya", name: "熊谷駅", baseId: 315 },
  { slug: "yokosuka", name: "横須賀駅", baseId: 316 },
  { slug: "yoshikawa", name: "吉川駅", baseId: 317 },
  { slug: "miyahara", name: "宮原駅", baseId: 318 },
  { slug: "konosu", name: "鴻巣駅", baseId: 319 },
  { slug: "anegasaki", name: "姉ケ崎駅", baseId: 322 },
  { slug: "morioka", name: "盛岡駅", baseId: 323 },
  { slug: "kamonomiya", name: "鴨宮駅", baseId: 324 },
  { slug: "sakura", name: "佐倉駅", baseId: 325 },
  { slug: "higashi-washinomiya", name: "東鷲宮駅", baseId: 326 },
  { slug: "tsuga", name: "都賀駅", baseId: 327 },
  { slug: "yumoto", name: "湯本駅", baseId: 328 },
  { slug: "musashi-shinjo", name: "武蔵新城駅", baseId: 329 },
  { slug: "yonezawa", name: "米沢駅", baseId: 330 },
  { slug: "kansai-international-airport", name: "関西国際空港駅", baseId: 331 },
  { slug: "osaka-international-airport", name: "大阪国際空港駅", baseId: 332 },
  { slug: "osaka-metro-esaka", name: "Osaka Metro 江坂駅", baseId: 333 },
  { slug: "osaka-metro-higashi-mikuni", name: "Osaka Metro 東三国駅", baseId: 334 },
  { slug: "osaka-metro-umeda", name: "Osaka Metro 梅田駅", baseId: 335 },
  { slug: "osaka-metro-tennoji", name: "Osaka Metro 天王寺駅", baseId: 336 },
  { slug: "osaka-metro-shinsaibashi", name: "Osaka Metro 心斎橋駅", baseId: 337 },
  { slug: "ichinoseki", name: "一ノ関駅", baseId: 338 },
  { slug: "yamagata", name: "山形駅", baseId: 339 },
  { slug: "echigoyuzawa", name: "越後湯沢駅", baseId: 340 },
  { slug: "osaka-metro-higashiumeda", name: "Osaka Metro 東梅田駅", baseId: 341 },
  { slug: "osaka-metro-takaita", name: "Osaka Metro 高井田駅", baseId: 342 },
  { slug: "osaka-metrotenjimbashisuji-6-chome", name: "Osaka Metro 天神橋筋六丁目駅", baseId: 343 },
  { slug: "osaka-metro-shin-osaka", name: "Osaka Metro 新大阪駅", baseId: 344 },
  { slug: "osaka-metro-nagai", name: "Osaka Metro 長居駅", baseId: 345 },
  { slug: "osaka-metro-deto", name: "Osaka Metro 出戸駅", baseId: 346 },
  { slug: "osaka-metro-kireuriwari", name: "Osaka Metro 喜連瓜破駅", baseId: 347 },
  { slug: "hankyu-osaka-umeda", name: "阪急 大阪梅田駅", baseId: 348 },
  { slug: "railway-museum", name: "鉄道博物館駅", baseId: 349 },
  { slug: "ishioka", name: "石岡駅", baseId: 350 },
  { slug: "tsuchiura", name: "土浦駅", baseId: 351 },
  { slug: "yakushiji-temple", name: "薬師寺駅", baseId: 352 },
  { slug: "maebashi", name: "前橋駅", baseId: 353 },
  { slug: "zushi", name: "逗子駅", baseId: 354 },
  { slug: "higashi-kanagawa", name: "東神奈川駅", baseId: 355 },
  { slug: "higashi-kawaguchi", name: "東川口駅", baseId: 356 },
  { slug: "yokohama-municipal-subway-kannai", name: "横浜市営地下鉄 関内駅", baseId: 357 },
  { slug: "yokohama-municipal-subway-shin-yokohama", name: "横浜市営地下鉄 新横浜駅", baseId: 358 },
  { slug: "tsuruoka", name: "鶴岡駅", baseId: 359 },
  { slug: "sakata", name: "酒田駅", baseId: 360 },
  { slug: "murakami", name: "村上駅", baseId: 361 },
  { slug: "ajiro", name: "網代駅", baseId: 363 },
  { slug: "katsunuma-budokyo", name: "勝沼ぶどう郷駅", baseId: 364 },
  { slug: "sagamiko", name: "相模湖駅", baseId: 365 },
  { slug: "osaka-metro-yao-minami", name: "Osaka Metro 八尾南駅", baseId: 366 },
  { slug: "osaka-metro-nagahara", name: "Osaka Metro 長原駅", baseId: 367 },
  { slug: "osaka-metro-osaka-business-park", name: "Osaka Metro 大阪ビジネスパーク駅", baseId: 368 },
  { slug: "osaka-metro-namba", name: "Osaka Metro なんば駅", baseId: 369 },
  { slug: "osaka-metro-nakazakicho", name: "Osaka Metro 中崎町駅", baseId: 370 },
  { slug: "osaka-metro-ogimachi", name: "Osaka Metro 扇町駅", baseId: 371 },
  { slug: "osaka-metro-nakatsu", name: "Osaka Metro 中津駅", baseId: 372 },
  { slug: "chibaminato", name: "千葉みなと駅", baseId: 373 },
  { slug: "akigawa", name: "秋川駅", baseId: 374 },
  { slug: "yamadera", name: "山寺駅", baseId: 375 },
  { slug: "aeon-laketown-mori", name: "イオンレイクタウンmori駅", baseId: 376 },
  { slug: "osaka-metro-gamoyonchome", name: "Osaka Metro 蒲生四丁目駅", baseId: 377 },
  { slug: "osakametroimafukutsurumieki", name: "Osaka Metro 今福鶴見駅", baseId: 378 },
  { slug: "osaka-metro-dobutsuen-mae", name: "Osaka Metro 動物園前駅", baseId: 379 },
  { slug: "osaka-metro-hirano", name: "Osaka Metro 平野駅", baseId: 380 },
  { slug: "osaka-metro-fuminosato", name: "Osaka Metro 文の里駅", baseId: 381 },
  { slug: "osaka-metro-hommachi", name: "Osaka Metro 本町駅", baseId: 382 },
  { slug: "osaka-metro-kyobashi", name: "Osaka Metro 京橋駅", baseId: 383 },
  { slug: "ome", name: "青梅駅", baseId: 384 },
  { slug: "tokyu-sangen-jaya", name: "東急 三軒茶屋駅", baseId: 385 },
  { slug: "toke", name: "土気駅", baseId: 386 },
  { slug: "tokyu-den-en-chofu", name: "東急 田園調布駅", baseId: 388 },
  { slug: "takasaki-opa", name: "高崎オーパ駅", baseId: 389 },
  { slug: "hanamaki", name: "花巻駅", baseId: 390 },
  { slug: "same", name: "鮫駅", baseId: 395 },
  { slug: "honhachinohe", name: "本八戸駅", baseId: 396 },
  { slug: "hachinohe", name: "八戸駅", baseId: 397 },
  { slug: "shinsugita", name: "新杉田駅", baseId: 399 },
  { slug: "akita", name: "秋田駅", baseId: 400 },
  { slug: "hiraizumi", name: "平泉駅", baseId: 401 },
  { slug: "osaka-metro-yotsubashi", name: "Osaka Metro 四ツ橋駅", baseId: 404 },
  { slug: "osaka-metro-nagahoribashi", name: "Osaka Metro 長堀橋駅", baseId: 405 },
  { slug: "osaka-metro-abeno", name: "Osaka Metro 阿倍野駅", baseId: 406 },
  { slug: "shinmisato", name: "新三郷駅", baseId: 411 },
  { slug: "tokyu-tama-plaza", name: "東急 たまプラーザ駅A", baseId: 412 },
  { slug: "sagamihara", name: "相模原駅", baseId: 413 },
];

// マルチエキューブのサイズ区分。実運用でsm/ml/xl/tlが使われている例は確認できていない。
// 内寸(FAQ https://multiecube.com/faq/ に記載、2026-07-12確認)。LWは公式記載が見当たらず不明のため空欄。
const SIZE_TIERS = [
  { key: "ss", label: "SS", dimensions: "34×65×15cm" },
  { key: "s", label: "S", dimensions: "34×65×33cm" },
  { key: "m", label: "M", dimensions: "34×65×50cm" },
  { key: "l", label: "L", dimensions: "34×65×86cm" },
  { key: "lw", label: "LW", dimensions: "" },
];

function normalizeLocation(loc, station, now) {
  const areaName = loc.area?.attributes?.display_name || "";
  let detailName = loc.attributes?.display_name || "";
  // マルチエキューブ側の名称に既に「付近」が含まれている場合があり、そのまま付けると重複するため除去
  detailName = detailName.replace(/付近$/, "");

  const sizes = [];
  for (const tier of SIZE_TIERS) {
    const box = loc.box_availability?.[tier.key];
    if (!box || box.num_total === 0) continue;
    sizes.push({
      size_type: tier.label,
      price: box.unreserve.price.basic + box.unreserve.price.std,
      quantity: box.num_total,
      dimensions: tier.dimensions,
    });
  }

  return {
    facility_id: loc.id,
    name: `${areaName} コインロッカー`,
    // マルチエキューブAPIは番地までの住所を返さないため、駅・改札・目印を組み合わせた説明文で代用
    address: `${station.name} ${areaName} ${detailName}付近`,
    latitude: Number(loc.latitude),
    longitude: Number(loc.longitude),
    nearest_station: station.name,
    station_slug: station.slug,
    business_hours: loc.attributes?.business_hours?.summary || "不明",
    source: {
      site_name: SOURCE_SITE_NAME,
      site_url: `https://multiecube.com/station/${station.baseId}`,
    },
    last_updated_at: now,
    sizes,
  };
}

async function fetchStationLocations(baseId) {
  const dateStr = todayJstDate();
  const results = [];
  let pageNo = 1;

  while (true) {
    const params = new URLSearchParams({
      includes_premium: "true",
      limit: "100",
      page_no: String(pageNo),
      service_type: "3,1",
      includes_no_empty: "false",
      base_id: String(baseId),
      end_at: dateStr,
      from_at: dateStr,
      lang: "ja",
    });

    const res = await fetch(`${API_BASE}?${params.toString()}`, {
      headers: { Origin: "https://multiecube.com", Referer: "https://multiecube.com/" },
    });
    if (!res.ok) {
      throw new Error(`multiecube API ${res.status} ${res.statusText} (base_id=${baseId})`);
    }
    const data = await res.json();
    results.push(...(data.locations || []));

    if (!data.page_total || pageNo >= data.page_total) break;
    pageNo += 1;
  }

  return results;
}

module.exports = {
  id: "multiecube",
  siteName: SOURCE_SITE_NAME,
  async collect({ now }) {
    const results = [];
    for (const station of STATIONS) {
      try {
        const locations = await fetchStationLocations(station.baseId);
        const normalized = locations.map((loc) => normalizeLocation(loc, station, now));
        results.push({ slug: station.slug, locations: normalized });
      } catch (err) {
        results.push({ slug: station.slug, error: err.message });
      }
      // 対応駅数が増えたため、駅間に間隔を空けて短時間の連続アクセスを避ける
      await new Promise((resolve) => setTimeout(resolve, 300));
    }
    return results;
  },
};
